### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by kazumaxneo** [raw-lab/mercat2#12] opened 2024-05-17 11:28 UTC
Hi, 

I would like to analyze the similarity of a set of genome sequence (Vibrio stains) with mercat2's approach.
I installed mercat2 with mamba as instructed in the repository (using Python 3.10.14), and runned as follows.
I noticed the error happen only when multi sample (2≥) were supplied to the program.
How should I deal with this ?

best,

=============================================================================
$ cp GCF*fna test/
$ mercat2.py -f test/ -k 3 -n 8 -c 10
.
.
...
GCF_024442235.1 .fna
GCF_028743655.1 .fna
GCF_025917725.1 .fna
GCF_003691505.1 .fna
GCF_009665315.1 .fna
GCF_003691545.1 .fna
GCF_001310575.2 .fna
GCF_022453845.1 .fna
GCF_002887655.1 .fna
GCF_002021755.1 .fna
Time to load 16 files: 8.51 seconds
Checking for large nucleotide files
Processing Nucleotides
Running Mercat2 using 18 cores
Time to count 3-mers: 1.71 seconds

Creating Nucleotide Graphs
/home/kazu/mambaforge/envs/mercat2/lib/python3.10/site-packages/sklearn/metrics/pairwise.py:2317: DataConversionWarning:

Data was converted to boolean for metric dice

/home/kazu/mambaforge/envs/mercat2/lib/python3.10/site-packages/sklearn/metrics/pairwise.py:2317: DataConversionWarning:

Data was converted to boolean for metric jaccard

Error with beta metric: Mahalanobis
Data must be symmetric and cannot contain NaNs.
/home/kazu/mambaforge/envs/mercat2/lib/python3.10/site-packages/sklearn/metrics/pairwise.py:2317: DataConversionWarning:

Data was converted to boolean for metric matching

/home/kazu/mambaforge/envs/mercat2/lib/python3.10/site-packages/sklearn/metrics/pairwise.py:2317: DataConversionWarning:

Data was converted to boolean for metric rogerstanimoto

/home/kazu/mambaforge/envs/mercat2/lib/python3.10/site-packages/sklearn/metrics/pairwise.py:2317: DataConversionWarning:

Data was converted to boolean for metric russellrao

/home/kazu/mambaforge/envs/mercat2/lib/python3.10/site-packages/sklearn/metrics/pairwise.py:2317: DataConversionWarning:

Data was converted to boolean for metric sokalmichener

/home/kazu/mambaforge/envs/mercat2/lib/python3.10/site-packages/sklearn/metrics/pairwise.py:2317: DataConversionWarning:

Data was converted to boolean for metric sokalsneath

/home/kazu/mambaforge/envs/mercat2/lib/python3.10/site-packages/sklearn/metrics/pairwise.py:2317: DataConversionWarning:

Data was converted to boolean for metric yule

Gathering Diversity Metrics
Traceback (most recent call last):
  File "/home/kazu/mambaforge/envs/mercat2/bin/mercat2.py", line 508, in <module>
    mercat_main()
  File "/home/kazu/mambaforge/envs/mercat2/bin/mercat2.py", line 499, in mercat_main
    mercat2_report.merge_tsv(tomerge, outfile)
  File "/home/kazu/mambaforge/envs/mercat2/lib/python3.10/site-packages/mercat2_lib/mercat2_report.py", line 128, in merge_tsv
    kmer = sorted(kmers)[0]
IndexError: list index out of range

**Comment by decrevi** [comment] 2024-05-21 21:47
Hello,
I was able to re-create the error and track down the bug.
The issue is actually in the naming of the files when merging the diversity metrics tsv files, a regex fails due to the "." (dot) in the file name. I am working on a patch and can post an update, but in the meantime you can try renaming the files to remove the dot in the filename, e.g. instead of GCF_024442235.1.fna rename it to GCF_024442235_1.fna

Sorry for the inconvenience, and thank you for using MerCat2.
-Jose

**Comment by kazumaxneo** [comment] 2024-05-22 06:22
Hi decrevi,

Great !, sorry for the problems.
Mercat2 worked perfectly after renaming.
Thank you very much.

Best,

**Comment by raw-lab** [comment] 2024-05-22 07:13
No problem at all. Thanks for finding this bug for us. We are always trying to improve our code bases and make them more user friendly. 

Thank you for using MerCat2. Tell your friends. 
I am going to close this for now. 

Let us know if you need anything?

**Closed as completed by raw-lab** 2024-05-22 07:13 UTC
